# Generated by Django 3.2.8 on 2022-03-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('slug', models.SlugField(max_length=200, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('image', models.ImageField(upload_to='books/', verbose_name='Картинка')),
                ('description', models.TextField(verbose_name='Описание')),
                ('isbn', models.PositiveIntegerField(verbose_name='ISBN')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год')),
                ('slug', models.SlugField(max_length=200, verbose_name='Слаг')),
                ('authors', models.ManyToManyField(related_name='authors', to='books.Author', verbose_name='Авторы')),
                ('genres', models.ManyToManyField(related_name='genres', to='books.Genre', verbose_name='Жанры')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
