# Generated by Django 3.2.8 on 2022-04-21 04:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0006_book_bookmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='bookmark',
        ),
        migrations.AddField(
            model_name='book',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, null=True, related_name='bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='В закладках у'),
        ),
    ]
