# Generated by Django 3.2.8 on 2022-04-21 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20220421_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='bookmarks',
            new_name='users',
        ),
    ]
